// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filter.proto

package filter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValueFilter struct {
	Include              []string `protobuf:"bytes,1,rep,name=include" json:"include,omitempty"`
	Exclude              []string `protobuf:"bytes,2,rep,name=exclude" json:"exclude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueFilter) Reset()         { *m = ValueFilter{} }
func (m *ValueFilter) String() string { return proto.CompactTextString(m) }
func (*ValueFilter) ProtoMessage()    {}
func (*ValueFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{0}
}

func (m *ValueFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueFilter.Unmarshal(m, b)
}
func (m *ValueFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueFilter.Marshal(b, m, deterministic)
}
func (m *ValueFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueFilter.Merge(m, src)
}
func (m *ValueFilter) XXX_Size() int {
	return xxx_messageInfo_ValueFilter.Size(m)
}
func (m *ValueFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ValueFilter proto.InternalMessageInfo

func (m *ValueFilter) GetInclude() []string {
	if m != nil {
		return m.Include
	}
	return nil
}

func (m *ValueFilter) GetExclude() []string {
	if m != nil {
		return m.Exclude
	}
	return nil
}

var E_File = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*ValueFilter)(nil),
	Field:         61255,
	Name:          "filter.file",
	Tag:           "bytes,61255,opt,name=file",
	Filename:      "filter.proto",
}

var E_Service = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*ValueFilter)(nil),
	Field:         61255,
	Name:          "filter.service",
	Tag:           "bytes,61255,opt,name=service",
	Filename:      "filter.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*ValueFilter)(nil),
	Field:         61255,
	Name:          "filter.method",
	Tag:           "bytes,61255,opt,name=method",
	Filename:      "filter.proto",
}

var E_Enum = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*ValueFilter)(nil),
	Field:         61255,
	Name:          "filter.enum",
	Tag:           "bytes,61255,opt,name=enum",
	Filename:      "filter.proto",
}

var E_EnumValue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*ValueFilter)(nil),
	Field:         61255,
	Name:          "filter.enum_value",
	Tag:           "bytes,61255,opt,name=enum_value",
	Filename:      "filter.proto",
}

var E_Message = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*ValueFilter)(nil),
	Field:         61255,
	Name:          "filter.message",
	Tag:           "bytes,61255,opt,name=message",
	Filename:      "filter.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*ValueFilter)(nil),
	Field:         61255,
	Name:          "filter.field",
	Tag:           "bytes,61255,opt,name=field",
	Filename:      "filter.proto",
}

var E_OneOf = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.OneofOptions)(nil),
	ExtensionType: (*ValueFilter)(nil),
	Field:         61255,
	Name:          "filter.one_of",
	Tag:           "bytes,61255,opt,name=one_of",
	Filename:      "filter.proto",
}

func init() {
	proto.RegisterType((*ValueFilter)(nil), "filter.ValueFilter")
	proto.RegisterExtension(E_File)
	proto.RegisterExtension(E_Service)
	proto.RegisterExtension(E_Method)
	proto.RegisterExtension(E_Enum)
	proto.RegisterExtension(E_EnumValue)
	proto.RegisterExtension(E_Message)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_OneOf)
}

func init() { proto.RegisterFile("filter.proto", fileDescriptor_1f5303cab7a20d6f) }

var fileDescriptor_1f5303cab7a20d6f = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0xa9, 0xd5, 0x94, 0x4e, 0x3d, 0xad, 0x97, 0x20, 0x7e, 0x44, 0x4f, 0x3d, 0xa5, 0xe0,
	0x71, 0x6f, 0x1e, 0xac, 0xa0, 0x84, 0x48, 0x05, 0x3d, 0x96, 0x9a, 0xcc, 0xc6, 0x85, 0xcd, 0x4e,
	0xc8, 0x47, 0xf1, 0x0d, 0x7d, 0x0b, 0x9f, 0x45, 0x36, 0x9b, 0x40, 0xa1, 0x7b, 0xd8, 0x53, 0x98,
	0xfc, 0x66, 0x7e, 0x93, 0xf9, 0x07, 0xce, 0x85, 0x54, 0x2d, 0xd6, 0x71, 0x55, 0x53, 0x4b, 0x2c,
	0xb0, 0xd5, 0x65, 0x54, 0x10, 0x15, 0x0a, 0x57, 0xfd, 0xdb, 0xaf, 0x4e, 0xac, 0x72, 0x6c, 0xb2,
	0x5a, 0x56, 0x2d, 0x0d, 0x9d, 0xf7, 0x8f, 0xb0, 0xf8, 0xd8, 0xa9, 0x0e, 0xd7, 0xfd, 0x00, 0x0b,
	0x61, 0x26, 0x75, 0xa6, 0xba, 0x1c, 0xc3, 0x49, 0x34, 0x5d, 0xce, 0x37, 0x63, 0x69, 0x08, 0xfe,
	0x58, 0x72, 0x62, 0xc9, 0x50, 0xf2, 0x67, 0x38, 0x15, 0x52, 0x21, 0xbb, 0x8a, 0xed, 0xb6, 0x78,
	0xdc, 0x16, 0xaf, 0xa5, 0xc2, 0xb4, 0x6a, 0x25, 0xe9, 0x26, 0xfc, 0xfd, 0x9b, 0x46, 0x93, 0xe5,
	0xe2, 0xe1, 0x22, 0x1e, 0xbe, 0xf4, 0x60, 0xed, 0xa6, 0x17, 0xf0, 0x37, 0x98, 0x35, 0x58, 0xef,
	0x65, 0x86, 0xec, 0xf6, 0xc8, 0xf5, 0x6e, 0x89, 0x97, 0x6e, 0xd4, 0xf0, 0x04, 0x82, 0x12, 0xdb,
	0x6f, 0xca, 0xd9, 0xcd, 0x91, 0x30, 0xe9, 0x81, 0x97, 0x6f, 0x90, 0x98, 0x4b, 0x51, 0x77, 0xa5,
	0xe3, 0xd2, 0x27, 0xdd, 0x95, 0x7e, 0x97, 0x1a, 0x01, 0xff, 0x04, 0x30, 0xcf, 0xed, 0xde, 0x10,
	0x76, 0xe7, 0xd4, 0xf5, 0x53, 0x5e, 0xce, 0x39, 0x8e, 0xed, 0x26, 0xc2, 0x12, 0x9b, 0x66, 0x57,
	0xb8, 0x22, 0x4c, 0x2c, 0xf1, 0x8b, 0x70, 0xd0, 0xf0, 0x17, 0x38, 0x13, 0x12, 0x55, 0xce, 0xae,
	0x1d, 0xbf, 0x17, 0x95, 0x5f, 0x80, 0x56, 0xc1, 0x5f, 0x21, 0x20, 0x8d, 0x5b, 0x12, 0x0e, 0x59,
	0xaa, 0x91, 0x84, 0x9f, 0x8c, 0x34, 0xa6, 0xe2, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x8c, 0xf4,
	0x8d, 0xf2, 0x02, 0x00, 0x00,
}
